### ISSUE TITLE
分散負載有辦法Proxy端皆支援tls嗎？

### ISSUE THREAD

**Issue by lawrence1751** [master-coder-ll/v2ray-web-manager#109]
## 你的问题是什么？
想請問分散式負載模式，有辦法將其他VPS也開啟443且啟用TLS模式嗎？

有看這篇模式[(v2ray-web-manager模式和配置)](https://github.com/master-coder-ll/v2ray-web-manager/blob/master/step-by-step-model.md#v2ray-web-manager%E6%A8%A1%E5%BC%8F%E5%92%8C%E9%85%8D%E7%BD%AE)解說，想請問文章內寫

> proxy端不提供tls支援

意思是我如果新增第二個節點實現分散式負載，無法使用443並開啟tls嗎？

我目前想這樣做: 
VPS1 有admin.jar 主站但不創建伺服器: https://a.domain.com
VPS2 無admin.jar: only v2ray-proxy (443+tls on) https://b.domain.com
VPS3 無admin.jar: only v2ray-proxy (443+tls on) https://c.domain.com

## 出现问题的情况是怎么样的？

VPS2/3 無法在 443+tls on的時候開起log紀錄(java已啟用)亦無法連接

這是我的VPS 2/3 的nginx文件內容(b.domain.com已申請好證書):

```
server {
    listen 443 ssl http2;
    server_name b.domain.com;
    ssl_certificate       /etc/nginx/ssl_cert/b.domain.com/b.domain.com;
    ssl_certificate_key   /etc/nginx/ssl_cert/b.domain.com/b.domain.com;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers TLS13-AES-128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC
4;
    location /ws/ {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:8081;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
server {
    listen 80;
    server_name b.domain.com;
    return 301 https:///$http_host$request_uri;
}
```
我的VPS2 proxy.yaml內容:

```
proxy:
  authPassword: passwordinadmin
  localPort: 8081
  maxConnections: 300
logging:
  file: /opt/jar/logs/v2ray-proxy.log
  file.max-history: 7
  level:
    root: info
manager:
  #如果admin端不在本机需要修改
  address: http://a.domain.com:9091
  getProxyAccountUrl: ${manager.address}/proxy/proxyAccount/ac?accountNo={accountNo}&domain={domain}
  reportFlowUrl: ${manager.address}/report/flowStat
  reportOverConnectionLimitUrl: ${manager.address}/report/connectionLimit?accountNo={accountNo}
server:
  port: 8091
  tomcat:
    max-threads: 1
    min-threads: 1
```
經測試Client無法使用v2ray+websocket+https(443)連線到VPS2
管理端伺服器列表介面已將TLS開啟、端口選擇443、訪問域名改為b.domain.com

但無法連線b.domain.com成功

謝謝！！
